/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#3d6922",
        "primary-container": "#93c572",
        "on-primary": "#ffffff",
        "on-primary-container": "#27520b",
        "primary-fixed": "#bdf199",
        "primary-fixed-dim": "#a2d580",
        secondary: "#77574d",
        "secondary-container": "#fed3c7",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#795950",
        tertiary: "#a43c12",
        "tertiary-container": "#ff9e7c",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#842800",
        "tertiary-fixed": "#ffdbcf",
        "tertiary-fixed-dim": "#ffb59c",
        background: "#fbf9f5",
        surface: "#fbf9f5",
        "surface-dim": "#dbdad6",
        "surface-bright": "#fbf9f5",
        "surface-container": "#efeeea",
        "surface-container-low": "#f5f3ef",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#eae8e4",
        "surface-container-highest": "#e4e2de",
        "on-surface": "#1b1c1a",
        "on-surface-variant": "#42493c",
        outline: "#73796b",
        "outline-variant": "#c2c9b8",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        display: ["Epilogue", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
      },
    },
  },
  plugins: [],
}
